// Code generated by thriftgo (0.3.10). DO NOT EDIT.

package java

import (
	java "github.com/s5364733/codec-dubbo/java"
)

type Object = java.Object

var NewObject = java.NewObject

type Date = java.Date

var NewDate = java.NewDate

type Exception = java.Exception

var NewException = java.NewException
