// Code generated by thriftgo (0.3.10). DO NOT EDIT.

package extensions

import (
	"reflect"

	"github.com/cloudwego/thriftgo/thrift_reflection"
)

// IDL Name: extensions
// IDL Path: extensions.thrift
// Remote Path: github.com/kitex-contrib/codec-dubbo-tests/code/kitex/extensions

var file_extensions_thrift *thrift_reflection.FileDescriptor

func init() {
	if file_extensions_thrift != nil {
		return
	}
	type x struct{}
	replacer := &thrift_reflection.FileDescriptorReplacer{
		RemoteGoPkgPath:  `github.com/kitex-contrib/codec-dubbo-tests/code/kitex/extensions`,
		CurrentGoPkgPath: reflect.TypeOf(x{}).PkgPath(),
		CurrentFilepath:  `extensions.thrift`,
		Matcher:          "BigDecimal",
	}
	file_extensions_thrift = thrift_reflection.ReplaceFileDescriptor(replacer)
}

func GetFileDescriptorForExtensions() *thrift_reflection.FileDescriptor {
	return file_extensions_thrift
}
