// Code generated by thriftgo (0.3.10). DO NOT EDIT.

package extensions

import (
	extensions "github.com/kitex-contrib/codec-dubbo-tests/code/kitex/extensions"
)

type BigDecimal = extensions.BigDecimal

var NewBigDecimal = extensions.NewBigDecimal

type BigInteger = extensions.BigInteger

var NewBigInteger = extensions.NewBigInteger
